server:
  port: ${PORT:8100}

spring:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_HOST:localhost:29092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: my-consumer-group
